Tabemashou Admin/Models/Dish.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Tabemashou_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dish()
        {
            this.DishesByCheck = new HashSet<DishesByCheck>();
            this.DishesPerLocal = new HashSet<DishesPerLocal>();
            this.Photo = new HashSet<Photo>();
            this.Type = new HashSet<Type>();
        }
    
        public int IdDish { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(0, float.MaxValue, ErrorMessage = "Please enter a valid price")]
        public decimal Price { get; set; }
        public int IdRestaurant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DishesByCheck> DishesByCheck { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DishesPerLocal> DishesPerLocal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type> Type { get; set; }
    }
}

Tabemashou Admin/Controllers/DishesController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tabemashou_Admin.Models;
using Type = Tabemashou_Admin.Models.Type;

namespace Tabemashou_Admin.Controllers
{
    public class DishesController : Controller
    {
        private TabemashouEntities db = new TabemashouEntities();

        // GET: Dishes
        public ActionResult Index()
        {
            var dish = db.Dish.Include(d => d.Restaurant);
            return View(dish.ToList());
        }

        // GET: Dishes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dish.Find(id);
            if (dish == null)
            {
                return HttpNotFound();
            }
            return View(dish);
        }

        
        public byte[] FileUpload(HttpPostedFileBase file)
        {

            // save the image path path to the database or you can send image
            // directly to database
            // in-case if you want to store byte[] ie. for DB
            byte[] array;
            using (MemoryStream ms = new MemoryStream())
            {
                file.InputStream.CopyTo(ms);
                array = ms.GetBuffer();
            }

            return array;
        }

        // GET: Dishes1/Create
        public ActionResult Create(int? id)
        {
            DishRegister model = new DishRegister();
            model.dish = new Dish();
            model.restaurant = db.Restaurant.Find(id);
            db.PR_DeleteUnusedTypes();
            return View(model);
        }


        // POST: Dishes1/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(DishRegister model)
        {
            if (ModelState.IsValid)
            {
                Dish dish = model.dish;
                if (model.restTypesId != null)
                {
                    foreach (var typeId in model.restTypesId)
                    {
                        Type restType = db.Type.Find(typeId);
                        restType.Dish.Add(dish);
                        dish.Type.Add(restType);
                    }
                }
                dish.IdRestaurant = model.idRestaurant;
                db.Dish.Add(dish);

                if (model.uploadFilesNames != null)
                {
                    string[] uploadFiles = model.uploadFilesNames.Split(',');
                    for (int i = 0; i < Request.Files.Count; i++)
                    {
                        HttpPostedFileBase tmpFile = Request.Files[i];
                        if (tmpFile != null && uploadFiles.Any(name => name == tmpFile.FileName) && uploadFiles.Length > 0)
                        {
                            byte[] dbImage = FileUpload(tmpFile);
                            Photo tmpPhoto = new Photo();
                            tmpPhoto.Photo1 = dbImage;
                            db.Photo.Add(tmpPhoto);

                            dish.Photo.Add(tmpPhoto);
                            tmpPhoto.Dish.Add(dish);
                            uploadFiles = uploadFiles.Where(name => name != tmpFile.FileName).ToArray();
                        }
                    }
                }
                var locals = (from loc in db.Local
                    where loc.IdRestaurant == model.idRestaurant
                    select loc);
                foreach (var local in locals)
                {
                    DishesPerLocal dpl = new DishesPerLocal();
                    dpl.IdDish = model.dish.IdDish;
                    dpl.IdLocal = local.IdLocal;
                    dpl.State = true;
                    db.DishesPerLocal.Add(dpl);
                }
                db.SaveChanges();
                return RedirectToAction("Index", "Locals", new { id = dish.IdRestaurant });
            }
            model.restaurant = db.Restaurant.Find(model.idRestaurant);
            return View(model);
        }

        // GET: Dishes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dish.Find(id);
            if (dish == null)
            {
                return HttpNotFound();
            }

            DishRegister model = new DishRegister
            {
                dish = dish,
                photos = db.Photo.ToList().Where(m => m.Dish.Any(n => n.IdDish == dish.IdDish)),
                restaurant = db.Restaurant.Find(dish.IdRestaurant),
                deletedFilesIds = "",
                uploadFilesNames = "",
                idRestaurant = dish.IdRestaurant,
                selectedItems = new MultiSelectList(db.Type, "IdType", "Name", dish.Type.Select(t => t.IdType))
        };
            db.PR_DeleteUnusedTypes();
            return View(model);
        }

        // POST: Dishes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(DishRegister model)
        {
            if (!ModelState.IsValid)
            {
                model.selectedItems = new MultiSelectList(db.Type, "IdType", "Name", model.dish.Type.Select(t => t.IdType));
                model.restaurant = db.Restaurant.Find(model.idRestaurant);
                model.photos = db.Photo.ToList().Where(m => m.Dish.Any(n => n.IdDish == model.dish.IdDish));
                model.deletedFilesIds = "";
                model.uploadFilesNames = "";
                return View(model);
            }
            if (model.restTypesId != null && model.restTypesId.Any())
            {
                String typeList = "";
                foreach (var typeId in model.restTypesId)
                {
                    typeList += typeId + ",";
                }
                db.PR_UpdateDishTypes(model.dish.IdDish, typeList.Remove(typeList.Length - 1));
            }
            else
            {
                db.PR_DeleteDishTypes(model.dish.IdDish);
            }

            Dish dish = db.Dish.Find(model.dish.IdDish);
            dish.Name = model.dish.Name;
            dish.Description = model.dish.Description;
            dish.Price = model.dish.Price;
            db.Entry(dish).State = EntityState.Modified;

            if (model.deletedFilesIds != null)
            {
                foreach (var idPhotoDelete in model.deletedFilesIds.Split(','))
                {
                    db.PR_DeleteDishPhoto(dish.IdDish, int.Parse(idPhotoDelete));
                }
            }

            if (model.uploadFilesNames != null)
            {
                string[] uploadFiles = model.uploadFilesNames.Split(',');
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase tmpFile = Request.Files[i];
                    if (tmpFile != null && uploadFiles.Any(name => name == tmpFile.FileName) &&
                        uploadFiles.Length > 0)
                    {
                        byte[] dbImage = FileUpload(tmpFile);
                        Photo tmpPhoto = new Photo();
                        tmpPhoto.Photo1 = dbImage;
                        db.Photo.Add(tmpPhoto);

                        dish.Photo.Add(tmpPhoto);
                        tmpPhoto.Dish.Add(dish);
                        uploadFiles = uploadFiles.Where(name => name != tmpFile.FileName).ToArray();
                    }
                }
            }

            db.SaveChanges();
            TempData["Success"] = dish.Name + " edited successfully.";
            return RedirectToAction("Index", "Locals", new { id = dish.IdRestaurant });
        }

        // GET: Dishes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dish.Find(id);
            if (dish == null)
            {
                return HttpNotFound();
            }
            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            int RestId;
            string dishName;
            using (TabemashouEntities dc = new TabemashouEntities())
            {
                Dish dish = dc.Dish.Find(id);
                dishName = dish.Name;
                RestId = dish.IdRestaurant;
            }
            TempData["Success"] = dishName + " deleted successfully.";
            db.PR_DeleteDish(id);
            db.SaveChanges();
            return RedirectToAction("Index","Locals",new {id = RestId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tabemashou Admin/Views/Dishes/Create.cshtml
@using Tabemashou_Admin.Models
@model DishRegister

@{
    ViewBag.Title = "Create a Dish";
    ViewBag.Breadcrumb = new Breadcrumb(new[]{
            new Crumb("Restaurants", @Url.Action("Index","Restaurants"), "fa-cutlery"),
            new Crumb(Model.restaurant.Name, @Url.Action("Index", "Locals", new { id =  Model.restaurant.IdRestaurant })),
            new Crumb("Menu", "", "fa-spoon"),
            new Crumb("Create", "", ""),

    });
}

@Styles.Render("~/AdminLTE/plugins/select2/css")
@Styles.Render("~/AdminLTE/dist/css")

@if (!ViewContext.ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-ban"></i> Error!</h4>
        @Html.ValidationSummary("", new { @class = "text" })
    </div>
}
<div class="col-md-12">
    <div class="box box-solid box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Register a new Dish
            </h3>
            <div class="box-tools pull-right">
            </div>
        </div>
        <div class="box-body">
            @using (Html.BeginForm("Create", "Dishes", FormMethod.Post, new { enctype = "multipart/form-data", data_ajax = "false" }))
            {
                @Html.HiddenFor(model=> model.idRestaurant, new {@Value = Model.restaurant.IdRestaurant})
                <div class="row">
                    <div class="col-md-12">
                        <div class="box box-solid box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title">Information</h3>
                                <div class="box-tools pull-right"></div>
                            </div>
                            <div class="box-body">
                                <div class="col-md-8">
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.dish.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.dish.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.dish.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.dish.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                    
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.dish.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                                                @Html.EditorFor(model => model.dish.Price, new { htmlAttributes = new { @class = "form-control", type = "number", step = "any", min = 0 } })
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.restaurant.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-8">
                                            @Html.ListBoxFor(m => m.restTypesId, new SelectList((new TabemashouEntities()).Type, "IdType", "Name"))
                                        </div>
                                        <div class="col-md-2">
                                            <button type="button" data-toggle="modal" data-target="#modalAddType" class="btn btn-block btn-success">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box box-solid box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title">Photos</h3>
                                <div class="box-tools pull-right" id="filecontainer">
                                    @Html.HiddenFor(model => model.uploadFilesNames)
                                    <input type="file" name="files[]" id="uploadFiles" accept=".jpg,.jpeg,.png" multiple />
                                </div>
                            </div>
                            <div class="row timeline-body" id="contentImages"></div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="form-group">
                        <a class="btn btn-default" href="@Url.Action("Index", "Locals", new { id =  Model.restaurant.IdRestaurant })">Back to List</a>
                        <button type="submit" value="Create" class="btn btn-info pull-right">Submit</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="modal" id="modalAddType">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title"> Create a Type</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.tipos.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.tipos.Name, new { htmlAttributes = new { @class = "form-control", type= "text" } })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger pull-left" data-dismiss="modal">Cancel</button>
                <button type="button" id="createType" class="btn btn-primary">Create</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/select2/js")
    @Scripts.Render("~/Scripts/Dishes/Create")
}

Tabemashou Admin/Views/Dishes/Delete.cshtml
@model Tabemashou_Admin.Models.Dish

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dish</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tabemashou Admin/Views/Dishes/Details.cshtml
@model Tabemashou_Admin.Models.Dish

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Dish</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdDish }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tabemashou Admin/Views/Dishes/Edit.cshtml
@using Tabemashou_Admin.Models
@model DishRegister

@{
    ViewBag.Title = "Edit a Dish";
    ViewBag.Breadcrumb = new Breadcrumb(new[]{
        new Crumb("Restaurants", @Url.Action("Index","Restaurants"), "fa-cutlery"),
        new Crumb(Model.restaurant.Name, @Url.Action("Index", "Locals", new { id = Model.idRestaurant })),
        new Crumb("Menu", "","fa-spoon"),
        new Crumb(Model.dish.Name, "", ""),

    });
}


@Styles.Render("~/AdminLTE/plugins/select2/css")
@Styles.Render("~/AdminLTE/dist/css")

@if (!ViewContext.ViewData.ModelState.IsValid )
{
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-ban"></i> Error!</h4>
        @Html.ValidationSummary("", new { @class = "text" })
    </div>
}

<div class="col-md-12">
    <div class="box box-solid box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Register a new Dish</h3>
            <div class="box-tools pull-right">
            </div>
        </div>
        <div class="box-body">
            @using (Html.BeginForm("Edit", "Dishes", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(model => model.idRestaurant)
                @Html.HiddenFor(model => model.dish.IdDish)
                <div class="row">
                    <div class="col-md-12">
                        <div class="box box-solid box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title">Information</h3>
                                <div class="box-tools pull-right">
                                </div>
                            </div>
                            <div class="box-body">
                                <div class="col-md-8">
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.dish.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.dish.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.dish.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.dish.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.dish.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                                                @Html.EditorFor(model => model.dish.Price, new { htmlAttributes = new { @class = "form-control", type = "number", step = "any", min = 0 } })

                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.restaurant.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-8">
                                            @Html.ListBoxFor(m => m.restTypesId, Model.selectedItems)
                                        </div>
                                        <div class="col-md-2">
                                            <button type="button" data-toggle="modal" data-target="#modalAddType" class="btn btn-block btn-success">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="box box-solid box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Photos</h3>
                                    <div class="box-tools pull-right" id="filecontainer">
                                        @Html.HiddenFor(model => model.uploadFilesNames)
                                        @Html.HiddenFor(model => model.deletedFilesIds)
                                        <input type="file" name="files[]" id="uploadFiles" accept=".jpg,.jpeg,.png" multiple />
                                    </div>
                                </div>
                                <div class="row timeline-body" id="contentImages">
                                    @foreach (var photo in Model.photos)
                                    {
                                        <div class="col-md-3" style="overflow: hidden; height: 250px;margin-bottom:10px;" id="image_@photo.IdPhoto">
                                            <a class="fa fa-remove btn btn-danger" style="float:right;position: absolute;" OnClick="deleteImageId(this)" index-element="@photo.IdPhoto"></a>
                                            <img class='img-responsive img-rounded' src=@Url.Action("ShowPhotoById", "Locals", new {id = photo.IdPhoto}) />
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <a class="btn btn-default" href="@Url.Action("Index", "Locals", new {id = Model.idRestaurant})">Back to List</a>
                    <button type="submit" value="Submit" class="btn btn-info pull-right">Submit</button>
                </div>
            }
        </div>
    </div>
</div>


<div class="modal" id="modalAddType">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title"> Create a Type</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.tipos.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.tipos.Name, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger pull-left" data-dismiss="modal">Cancel</button>
                <button type="button" id="createType" class="btn btn-primary">Create</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/Dishes/Edit")
    @Scripts.Render("~/AdminLTE/plugins/select2/js")
}

Tabemashou Admin/Views/Dishes/Index.cshtml
@model IEnumerable<Tabemashou_Admin.Models.Dish>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurant.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdDish }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdDish }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdDish })
        </td>
    </tr>
}

</table>